-- COMENTÁRIO DE 1 LINHA
/* COMENTÁRIO DE MUITAS LINHAS*/


-- COMANDO PARA MENCIONAR QUAL BANCO QUERO UTILIZAR
use aula01;

-- CRIANDO TABELAS (VAZIAS)
Create Table aula01.eXEMPLO1 (
 ID INT,
CPF VARCHAR(45),
 NOME_cOMPLETO VARCHAR(255) ,
 Primary Key(ID),
 unique (cpf) 
);

Create Table aula01.eXEMPLO2 (
 ID INT,
 APELIDO VARCHAR (255) NOT NULL ,
ID_NOME INT,
 Primary Key (ID),
 Foreign Key (ID_NOME) references EXEMPLO1(ID)
 );
 
 -- PRIMARY KEY: CRIAR CHAVE PRIMÁRIA
 -- FOREING KEY: CRIAR CHAVE ESTRANGEIRA
 
-- EXIBINDO AS TABELAS QUE EXISTEM  
 show tables;

-- DESCREVENDO A ESTRUTURA DE UMA TABELA 
 desc exemplo1;