-- COMENTÁRIO DE 1 LINHA
/* COMENTÁRIO DE MUITAS LINHAS*/

create database `aula05`;

-- COMANDO PARA MENCIONAR QUAL BANCO QUERO UTILIZAR
use aula05;

-- CRIANDO TABELAS (VAZIAS)
Create Table Aluno (
 ID INT,
 CPF VARCHAR(45),
 EMAIL VARCHAR(70),
 NOME_COMPLETO VARCHAR(255) ,
 Primary Key(ID),
 unique (cpf) 
);

ALTER TABLE Aluno 
	ADD COLUMN GENERO VARCHAR(10);

ALTER TABLE Aluno
	DROP COLUMN GENERO;
    
ALTER TABLE Aluno
	MODIFY COLUMN CPF INT (11);
    
ALTER TABLE Aluno
	CHANGE COLUMN NOME_COMPLETO NOME VARCHAR(60);

ALTER TABLE Aluno 
		RENAME TO Estudante;
        
        
-- EXIBINDO AS TABELAS QUE EXISTEM  
 show tables;

-- DESCREVENDO A ESTRUTURA DE UMA TABELA 
 -- desc Aluno;
 desc Estudante;