CREATE DATABASE CADASTROFUNCIONARIO;
USE CADASTROFUNCIONARIO;

CREATE TABLE FUNCIONARIOS (
	COD_CLI INT PRIMARY KEY NOT NULL,
	CODIGO  VARCHAR (50),
	PRIMEIRONOME VARCHAR (50),
	SEGUNDONOME VARCHAR (50),
	ULTIMONOME VARCHAR (50),
	DATANASCI DATE,
	CPF CHAR (50),
	ENDERECO VARCHAR (50),
	CEP VARCHAR(50),
	CIDADE VARCHAR (50), 
	FONE VARCHAR (11),
	CODIGODEPARTAMENTO INT, 
	FUNCAO VARCHAR (50),
	SALARIO VARCHAR (50) 
);

CREATE TABLE DEPARTAMENTOS (
COD_CLI INT PRIMARY KEY NOT NULL,
CODIGO VARCHAR(50),
NOME VARCHAR (50),
LOCALIZACAO VARCHAR (50),
CODIGOFUNCIONARIO INT, 
GERENTE VARCHAR (50)
);

INSERT INTO FUNCIONARIOS (COD_CLI, CODIGO, PRIMEIRONOME, SEGUNDONOME, ULTIMONOME, DATANASCI, CPF, ENDERECO, CEP, CIDADE, FONE, CODIGODEPARTAMENTO, FUNCAO, SALARIO)
 VALUE(4, "001", "ROBSON", "BAMBU", "HUMBERTO", 21/09/1985, "151.456.435-87", "RUA FATEC N°202", "65498-646", "RORAIMA", "(11) 98413-1967", 05, "OPERADOR", "R$1.000.000,00"), 
  (5, "002", "RUBENS", "BAMBU", "IMBRAIKMOVIK", 21/09/2005, "151.456.445-87", "RUA FATEC N°222", "65498-000", "RORAIMA", "(11) 94411-1967", 05, "OPERADOR", "R$1.000,00"),
  (6, "003", "RODINEI", "BAMBU", "EDINDIZEKO", 21/09/1900, "100.416.455-87", "RUA FATEC N°232", "65498-646", "RORAIMA", "(11) 99993-1967", 05, "OPERADOR", "R$5.000,00");

INSERT INTO DEPARTAMENTOS (COD_CLI, CODIGO, NOME, LOCALIZACAO, CODIGOFUNCIONARIO, GERENTE)
VALUE(10, 010, "EMEBAPE", "PARIS", 07, "MESSI"),
(11, 011, "AUBAMEYANG", "INGLATERRA", 09, "KANTE");

SELECT PRIMEIRONOME, ULTIMONOME
FROM FUNCIONARIOS
ORDER BY ULTIMONOME;

SELECT *
FROM FUNCIONARIOS
ORDER BY CIDADE;

SELECT *
FROM FUNCIONARIOS
WHERE SALARIO < 1000
ORDER BY PRIMEIRONOME, SEGUNDONOME, ULTIMONOME;

SELECT DATANASCI, PRIMEIRONOME
FROM FUNCIONARIOS
ORDER BY DATANASCI DESC,
PRIMEIRONOME;

SELECT ULTIMONOME, PRIMEIRONOME, SEGUNDONOME, FONE, ENDERECO, CIDADE
FROM FUNCIONARIOS
ORDER BY ULTIMONOME, PRIMEIRONOME, SEGUNDONOME;

SELECT SUM(SALARIO) AS TOTAL
FROM FUNCIONARIOS;

SELECT F.PRIMEIRONOME, D.NOME,
F.FUNCAO
FROM FUNCIONARIOS F JOIN
DEPARTAMENTOS D
ON F.CODIGODEPARTAMENTO = D.CODIGO
ORDER BY F.PRIMEIRONOME;

SELECT D.NOME, F.PRIMEIRONOME
FROM DEPARTAMENTOS D JOIN
FUNCIONARIOS F
ON D.CODIGOFUNCIONARIO = F.CODIGO
ORDER BY D.NOME;

SELECT D.NOME, SUM(F.SALARIO) AS 
TOTAL
FROM DEPARTAMENTOS D JOIN
FUNCIONARIOS F
ON D.CODIGO = F.CODIGODEPARTAMENTO
GROUP BY D.NOME;

SELECT D.NOME, F.PRIMEIRONOME
FROM DEPARTAMENTOS D JOIN
FUNCIONARIOS F
ON D.CODIGO = F.CODIGODEPARTAMENTO
WHERE F.FUNCAO = 'SUPERVISOR'
ORDER BY D.NOME;

SELECT COUNT(*) AS
TOTALFUNCIONARIOS
FROM FUNCIONARIOS;

SELECT AVG(SALARIO) AS MEDIA
FROM FUNCIONARIOS;

SELECT D.NOME, MIN(F.SALARIO) 
FROM FUNCIONARIOS F 
JOIN DEPARTAMENTOS D
ON F.CODIGODEPARTAMENTO = D.CODIGO 
GROUP BY D.NOME;

SELECT PRIMEIRONOME, SEGUNDONOME, ULTIMONOME
FROM FUNCIONARIOS
WHERE SEGUNDONOME IS NULL
ORDER BY PRIMEIRONOME, SEGUNDONOME;

SELECT D.NOME, F.PRIMEIRONOME
FROM DEPARTAMENTOS D JOIN
FUNCIONARIOS F ON D.CODIGO = F.CODIGODEPARTAMENTO
ORDER BY D.NOME, F.PRIMEIRONOME;

SELECT PRIMEIRONOME
FROM FUNCIONARIOS
WHERE CIDADE = 'RECIFE' AND Funcao 
= 'Telefonista';

SELECT PRIMEIRONOME
FROM FUNCIONARIOS
WHERE CODIGODEPARTAMENTO =
(SELECT CODIGO
FROM DEPARTAMENTOS
WHERE NOME = 'PESSOAL');

SELECT F.PRIMEIRONOME, D.NOME
FROM FUNCIONARIOS F JOIN DEPARTAMENTOS D
ON F.CODIGODEPARTAMENTO = D.CODIGO
WHERE F.SALARIO > SOME (
SELECT SALARIO
FROM FUNCIONARIOS
WHERE CODIGO IN (
SELECT CODIGOFUNCIONARIO
FROM DEPARTAMENTOS));